#***************************[help]********************************************
# 2018 01 30
function repo_help() {

    echo ""
    echo "### repo_help ###"
    echo ""
    echo "structure of all listed repositories:"
    echo "  ... == https://github.com/peterweissig"
    echo ""
    echo "  bash/"
    echo "      repo/               .../bash_repo.git"
    echo "      config/             .../bash_config.git"
    echo "      network/            .../bash_network.git"
    echo "      multimedia/         .../bash_multimedia.git"
    echo "      roboag/             .../bash_roboag.git"
    echo ""
    echo "  robo/"
    echo "      lib/                .../robolib.git"
    echo "      pololu/             https://github.com/pololu/libpololu-avr"
    echo ""
    echo "      eagle/"
    echo "          config/         .../eagle_config.git"
    echo "          keplerboard/    .../eagle_keplerboard.git"
    echo "          xbee/           .../eagle_xbee.git"
    echo "          logic/          .../eagle_logic.git"
    echo "          vtgMon/         .../eagle_voltageMonitoring.git"
    echo ""
    echo "      roboag/"
    echo "          gluecksrad/     .../proj_roboag_gluecksrad.git"
    echo "          3pi/            .../proj_roboag_3pi.git"
    echo ""
    echo "      robosax/"
    echo "          ledbox/         https://github.com/fabiangeissler/robosax-ledbox"
    echo "          licht_tht/      .../eagle_robosax_licht.git"
    echo "          licht_avr/      .../avr_robosax_licht.git"
    echo "          punkte/         .../php_robosax_punkte.git"
    echo ""
    echo "  projects/"
    echo "      eagle/"
    echo "          dmx_driver/     .../eagle_dmx_driver.git"
    echo "          dmx_opa/        .../eagle_dmx_opa.git"
    echo ""
    echo "      hardware/"
    echo "          audio_home/     .../proj_audio_home.git"
    echo "          dimmer/         .../project_dimmer.git"
    echo ""
    echo "      c++/                .../cpp_main.git"
    echo "        src/"
    echo "          basic/          .../cpp_basic.git"
    echo "          file/           .../cpp_file.git"
    echo "          comport/        .../cpp_comport.git"
    echo "          xbee_config/    .../cpp_xbee_config.git"
    echo "          avr_downloader/ .../cpp_avr_downloader.git"
    echo ""
    echo "  ros/"
    echo "    github/"
    echo "      src/"
    echo "        parameter/        .../ros_parameter.git"
    echo "        pcdfilter/        .../ros_pcdfilter.git"
    echo "        octomap/          .../ros_octomap.git"
    echo "        nearfield_map/    .../ros_nearfield_map.git"
    echo ""
    echo ""
    echo "specific commands"
    echo "  git_clone_xyz   ... copies/downloads  specified repository (xyz)"
    echo "  git_pull_xyz    ... updates           specified repository (xyz)"
    echo "  git_status_xyz  ... tracks changes of specified repository (xyz)"
    echo "  git_push_xyz    ... uploads           specified repository (xyz)"
    echo ""
    echo "general commands"
    echo "  repo_clone_all  ... copies/downloads  all repositories"
    echo "  repo_pull_all   ... updates           all repositories"
    echo "  repo_status_all ... tracks changes of all repositories"
    echo ""
}
