#***************************[help]********************************************
# 2018 04 1
function repo_help() {

    echo ""
    echo "### repo_help ###"
    echo ""
    echo "structure of all listed repositories:"
    echo "  [git] == https://github.com/"
    echo ""
    echo "  bash/"
    echo "      repo/               [git]/peterweissig/bash_repo.git"
    echo "      config/             [git]/peterweissig/bash_config.git"
    echo "      network/            [git]/peterweissig/bash_network.git"
    echo "      multimedia/         [git]/peterweissig/bash_multimedia.git"
    echo "      roboag/             [git]/roboag/bash_roboag.git"
    echo ""
    echo "  robo/"
    echo "      lib/                [git]/roboag/avr_robolib.git"
    echo "      pololu/             [git]/pololu/libpololu-avr"
    echo ""
    echo "      eagle/"
    echo "          config/         [git]/roboag/eagle_config.git"
    echo "          keplerboard/    [git]/roboag/eagle_keplerboard.git"
    echo "          xbee/           [git]/roboag/eagle_xbee.git"
    echo "          logic/          [git]/roboag/eagle_logic.git"
    echo "          vtgMon/         [git]/roboag/eagle_voltageMonitoring.git"
    echo ""
    echo "      roboag/"
    echo "          rotierendes_display/ [git]/roboag/projekt_display.git"
    echo "          gluecksrad/     [git]/roboag/projekt_gluecksrad.git"
    echo "          3pi/            [git]/roboag/projekt_3pi.git"
    echo "          filebrowser_php/ [git]/roboag/php_filebrowser.git"
    echo ""
    echo "      robosax/"
    echo "          ledbox/         [git]/robosax/projekt_ledbox"
    echo "          licht_tht/      [git]/robosax/eagle_licht.git"
    echo "          licht_avr/      [git]/robosax/avr_licht.git"
    echo "          anzeige_tht/    [git]/robosax/eagle_anzeige.git"
    echo "          punkte/         [git]/robosax/php_punkte.git"
    echo ""
    echo "  projects/"
    echo "      eagle/"
    echo "          dmx_driver/     [git]/peterweissig/eagle_dmx_driver.git"
    echo ""
    echo "      hardware/"
    echo "          audio_home/     [git]/peterweissig/project_audio_home.git"
    echo "          dmx_opa/        [git]/peterweissig/project_opa.git"
    echo "          dimmer/         [git]/peterweissig/project_dimmer.git"
    echo ""
    echo "      c++/                [git]/peterweissig/cpp_main.git"
    echo "        src/"
    echo "          basic/          [git]/peterweissig/cpp_basic.git"
    echo "          file/           [git]/peterweissig/cpp_file.git"
    echo "          comport/        [git]/peterweissig/cpp_comport.git"
    echo "          xbee_config/    [git]/peterweissig/cpp_xbee_config.git"
    echo "          avr_downloader/ [git]/peterweissig/cpp_avr_downloader.git"
    echo ""
    echo "  ros/"
    echo "    github/"
    echo "      src/"
    echo "        parameter/        [git]/peterweissig/ros_parameter.git"
    echo "        pcdfilter/        [git]/peterweissig/ros_pcdfilter.git"
    echo "        octomap/          [git]/peterweissig/ros_octomap.git"
    echo "        nearfield_map/    [git]/peterweissig/ros_nearfield_map.git"
    echo ""
    echo ""
    echo "specific commands"
    echo "  git_clone_xyz   ... copies/downloads  specified repository (xyz)"
    echo "  git_pull_xyz    ... updates           specified repository (xyz)"
    echo "  git_status_xyz  ... tracks changes of specified repository (xyz)"
    echo "  git_push_xyz    ... uploads           specified repository (xyz)"
    echo ""
    echo "general commands"
    echo "  repo_clone_all  ... copies/downloads  all repositories"
    echo "  repo_pull_all   ... updates           all repositories"
    echo "  repo_status_all ... tracks changes of all repositories"
    echo ""
}
